stash

diff --git a/development/php/Dockerfile b/development/php/Dockerfile
--- a/development/php/Dockerfile
+++ b/development/php/Dockerfile
@@ -3,6 +3,10 @@ FROM php:fpm-buster
 ARG TZ="Asia/Shanghai"
 
 ENV TZ ${TZ}
+ENV COMPOSER_ALLOW_SUPERUSER 1
+ENV COMPOSER_HOME /tmp
+ENV COMPOSER_VERSION 1.10.6
+
 RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list
 RUN sed -i 's/security.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list
 RUN apt-get update && apt-get install -y \
@@ -13,3 +17,17 @@ RUN apt-get update && apt-get install -y \
     && docker-php-ext-install -j$(nproc) gd
 RUN pecl install xdebug-2.8.1 \
     && docker-php-ext-enable xdebug
+RUN set -eux; \
+    curl --silent --fail --location --retry 3 --output /tmp/installer.php --url https://raw.githubusercontent.com/composer/getcomposer.org/cb19f2aa3aeaa2006c0cd69a7ef011eb31463067/web/installer; \
+    php -r " \
+    \$signature = '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5'; \
+    \$hash = hash('sha384', file_get_contents('/tmp/installer.php')); \
+    if (!hash_equals(\$signature, \$hash)) { \
+    unlink('/tmp/installer.php'); \
+    echo 'Integrity check failed, installer is either corrupt or worse.' . PHP_EOL; \
+    exit(1); \
+    }"; \
+    php /tmp/installer.php --no-ansi --install-dir=/usr/bin --filename=composer --version=${COMPOSER_VERSION}; \
+    composer --ansi --version --no-interaction; \
+    rm -f /tmp/installer.php; \
+    find /tmp -type d -exec chmod -v 1777 {} +
